[package]
name = "corrosion"
version = "0.1.0"
edition = "2024"

[dependencies]
egui-macroquad = "0.17.3"
macroquad = {version = "0.4.14" }
libcorr = { path = "./libcorr" }

[dev-dependencies]
divan = "0.1.21"

[[bench]]
name = "scene"
harness = false
required-features = ["bench"]

[features]
bench = []

[workspace]
resolver = "3"
members = ["libcorr"]

# [lib]
# crate-type = ["cdylib"]
